packages:
  - packages/*
  - apps/*
  - examples
  - benchmarks
  - tools

catalog:
  "@vitest/coverage-v8": 4.1.0
  oxfmt: 0.48.0
  oxlint: 1.55.0
  tsdown: 0.22.0
  typescript: 6.0.3
  vitest: 4.1.0

onlyBuiltDependencies:
  - esbuild
