packages:
  - packages/*
  - apps/*
  - examples
  - benchmarks
  - tools

catalog:
  "@vitest/coverage-v8": 4.1.9
  oxfmt: 0.48.0
  oxlint: 1.55.0
  oxlint-tsgolint: 0.23.0
  tsdown: 0.22.0
  typescript: 6.0.3
  vitest: 4.1.9

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false

ignoreScripts: true
allowBuilds:
  esbuild: true

overrides:
  vite: 8.0.16
  tsdown>unrun: 0.3.0
